services:
  mongo-service:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express

    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    ports:
      - 8081:8081
    networks:
      - mongo-network

volumes:
  mongo: {}
networks:
  mongo-network:
    driver: bridge